### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by ikazuchizero** [ikazuchizero/ikazuchizero#1]
多分このままだとDBがない
自分の環境でmongodbを使えるようにnabrさんに教えてもらう

**Comment by ikazuchizero** [comment]
たわしさんとぶたとブロック機能とかのDB使用している昨日を消してしまえばDBなしで動くのでは

**Comment by ikazuchizero** [comment]
prefixをDBで管理しているから無理なのでは
勉強してください

**Comment by nabr2730** [comment]
> 多分このままだとDBがない 自分の環境でmongodbを使えるようにnabrさんに教えてもらう

これはデータベースあとで作っておく〜

**Comment by ikazuchizero** [comment]
done
